extends "res://scripts/arena/flat_arena.gd"

const DOC = preload("res://scripts/maps/map_document.gd")
const GEOMETRY = preload("res://scripts/maps/map_geometry.gd")
var map_data: Dictionary = {}
var geometry: Node3D
var navigation: NavigationRegion3D
var navigation_ready := false
var validation_error := ""
var loading := true
var navigation_map := RID()
var infinite_ground: StaticBody3D


func _ready() -> void:
	super._ready()
	var floor_node := $Floor
	remove_child(floor_node)
	floor_node.queue_free()
	$PlayerSpawn.position = DOC.vector3(map_data.player_spawn)
	$PlayerSpawn.rotation.y = deg_to_rad(map_data.player_yaw)
	$TargetSpawn.position = DOC.vector3(map_data.bot_spawn)
	$TargetSpawn.rotation.y = deg_to_rad(map_data.bot_yaw)
	if map_data.get("infinite_ground", false):
		infinite_ground = preload("res://scripts/maps/infinite_ground.gd").new()
		# Outside the navigation subtree: infinite physics is not baking geometry.
		add_child(infinite_ground)
	navigation = NavigationRegion3D.new()
	navigation.name = "Navigation"
	# Baking stays threaded; publish this small static region synchronously once loaded.
	NavigationServer3D.region_set_use_async_iterations(navigation.get_rid(), false)
	navigation_map = NavigationServer3D.map_create()
	NavigationServer3D.map_set_active(navigation_map, true)
	NavigationServer3D.map_set_use_async_iterations(navigation_map, false)
	NavigationServer3D.map_set_cell_size(navigation_map, 0.25)
	NavigationServer3D.map_set_cell_height(navigation_map, 0.1)
	navigation.set_navigation_map(navigation_map)
	var mesh := NavigationMesh.new()
	mesh.geometry_parsed_geometry_type = NavigationMesh.PARSED_GEOMETRY_STATIC_COLLIDERS
	mesh.geometry_collision_mask = 1 | 32
	mesh.cell_size = 0.25
	mesh.cell_height = 0.1
	mesh.agent_radius = 0.5
	mesh.agent_height = 1.9
	mesh.agent_max_climb = 0.3
	mesh.agent_max_slope = 44.0
	var b: Array = map_data.bounds
	mesh.filter_baking_aabb = AABB(Vector3(b[0], -16, b[1]), Vector3(b[2] - b[0], 64, b[3] - b[1]))
	navigation.navigation_mesh = mesh
	add_child(navigation)
	navigation.set_navigation_map(navigation_map)
	geometry = Node3D.new()
	geometry.name = "Geometry"
	navigation.add_child(geometry)
	for item in map_data.objects:
		geometry.add_child(GEOMETRY.build_object(item))
	if infinite_ground != null:
		var proxy := StaticBody3D.new()
		proxy.name = "GroundBakeProxy"
		proxy.collision_layer = 32
		proxy.collision_mask = 0
		var collision := CollisionShape3D.new()
		var shape := BoxShape3D.new()
		shape.size = Vector3(b[2] - b[0] + 2, 1, b[3] - b[1] + 2)
		collision.shape = shape
		proxy.position = Vector3((b[0] + b[2]) * 0.5, -0.5, (b[1] + b[3]) * 0.5)
		proxy.add_child(collision)
		navigation.add_child(proxy)
	call_deferred("_prepare_navigation")


func _build_boundaries() -> void:
	# Custom maps own all geometry; autogenerated sibling names are not a cleanup contract.
	pass


func _prepare_navigation() -> void:
	await get_tree().physics_frame
	validation_error = validate_spawns()
	if not validation_error.is_empty():
		loading = false
		return
	navigation.bake_navigation_mesh(true)
	await navigation.bake_finished
	# Publish an immutable completed mesh, rather than a resource still owned by the baker.
	navigation.navigation_mesh = navigation.navigation_mesh.duplicate()
	# Let the server publish region data on its normal synchronization boundary.
	# Forcing updates while queued region work is still in flight can expose an empty map.
	await get_tree().process_frame
	await get_tree().physics_frame
	var map := navigation.get_navigation_map()
	var started := Time.get_ticks_msec()
	var synchronized := false
	while Time.get_ticks_msec() - started < 5000:
		var nearest := NavigationServer3D.map_get_closest_point(map, $PlayerSpawn.position)
		if NavigationServer3D.map_get_closest_point_owner(map, $PlayerSpawn.position).is_valid() \
			and nearest.distance_to($PlayerSpawn.position) < 0.75:
			synchronized = true
			break
		await get_tree().process_frame
		await get_tree().physics_frame
	navigation_ready = synchronized and navigation.navigation_mesh.get_polygon_count() > 0 \
		and NavigationServer3D.map_get_iteration_id(map) > 0
	if not navigation_ready:
		validation_error = "没有可行走的导航区域，请检查地板、净空和坡度。"
	else:
		var path := NavigationServer3D.map_get_path(map, $PlayerSpawn.position, $TargetSpawn.position, true)
		if path.is_empty() or path[0].distance_to($PlayerSpawn.position) > 0.75 \
			or path[path.size() - 1].distance_to($TargetSpawn.position) > 0.75:
			validation_error = "玩家与 Bot 出生点之间没有可行走的连通路径。"
			if "--integration" in OS.get_cmdline_user_args():
				print("NAV_DIAGNOSTIC polygons=", navigation.navigation_mesh.get_polygon_count(),
					" iteration=", NavigationServer3D.map_get_iteration_id(map),
					" regions=", NavigationServer3D.map_get_regions(map),
					" start=", $PlayerSpawn.position, " end=", $TargetSpawn.position,
					" near_start=", NavigationServer3D.map_get_closest_point(map, $PlayerSpawn.position),
					" near_end=", NavigationServer3D.map_get_closest_point(map, $TargetSpawn.position),
					" path=", path)
	loading = false


func _exit_tree() -> void:
	if navigation_map.is_valid():
		NavigationServer3D.free_rid(navigation_map)
		navigation_map = RID()


func validate_spawns() -> String:
	var space := get_world_3d().direct_space_state
	for marker in [$PlayerSpawn, $TargetSpawn]:
		var title := "玩家出生点" if marker == $PlayerSpawn else "Bot 出生点"
		var p: Vector3 = marker.global_position
		var floor_ray := PhysicsRayQueryParameters3D.create(p + Vector3.UP * 0.08, p - Vector3.UP * 0.45, 1)
		var floor_hit := space.intersect_ray(floor_ray)
		if floor_hit.is_empty() or floor_hit.normal.y < cos(deg_to_rad(44)):
			return "%s 下方 0.45 m 内需要有可行走地面。" % title
		var query := PhysicsShapeQueryParameters3D.new()
		var capsule := CapsuleShape3D.new()
		capsule.radius = 0.4
		capsule.height = 1.9
		query.shape = capsule
		query.transform.origin = p + Vector3.UP * 1.0
		query.collision_mask = 1
		if not space.intersect_shape(query, 1).is_empty():
			return "%s 与物体重叠，或头顶净空不足。" % title
	return ""


func apply_appearance(values: Dictionary) -> void:
	super.apply_appearance(values)
	if infinite_ground != null:
		infinite_ground.visual.material_override = floor_material
	if geometry == null:
		return
	for item in map_data.objects:
		var body := geometry.get_node("Object_%d" % int(item.id))
		for child in body.get_children():
			if child is MeshInstance3D:
				if item.kind == "box" and item.size[1] <= 1.0 and item.size[0] >= 4 and item.size[2] >= 4:
					var floor_surface: ShaderMaterial = floor_material.duplicate()
					if int(item.color) != 0:
						var color := Color(DOC.COLORS[int(item.color)])
						floor_surface.set_shader_parameter("floor_color", color)
						floor_surface.set_shader_parameter("grid_color", color.lightened(0.25))
					child.material_override = floor_surface
				else:
					var material := StandardMaterial3D.new()
					var color := Color(DOC.COLORS[int(item.color)])
					material.albedo_color = color.darkened(0.38) if int(values.arena_style) == 1 else color
					material.roughness = 0.9
					child.material_override = material


func contains_point(point: Vector3, margin: float = 0.0) -> bool:
	var b: Array = map_data.bounds
	return point.x >= b[0] + margin and point.x <= b[2] - margin \
		and point.z >= b[1] + margin and point.z <= b[3] - margin


func has_support(point: Vector3) -> bool:
	var query := PhysicsRayQueryParameters3D.create(point + Vector3.UP * 0.4, point - Vector3.UP * 0.65, 1)
	var hit := get_world_3d().direct_space_state.intersect_ray(query)
	return not hit.is_empty() and hit.normal.y >= cos(deg_to_rad(44))


func path_between(start: Vector3, end: Vector3) -> PackedVector3Array:
	if not navigation_ready:
		return PackedVector3Array()
	if not contains_point(start) or not contains_point(end):
		return PackedVector3Array()
	return NavigationServer3D.map_get_path(navigation.get_navigation_map(), start, end, true)
